.TH c00clupea 8
.SH NAME
c00clupea \-  just a honeypot
.SH SYNOPSIS
.B c00clupea
[\fB <options>]
.SH DESCRIPTION
c00clupea is just a honeypot and it doese what a honeypot needs to do...

<*)))><

Btw. c00 is red and clupea is lat.: for the family of Herring..
.SH OPTIONS

.IP -V
read the version and some info

.IP -h
get some help stuff

.IP -b
set the TCP Backlog (when you have too many single connections)

.IP "-c configfile"
use another configfile than the default one

.IP -s
set another default strategy

.SH CONTROLS
You are able to see some information when using signals

.IP "kill -30 <pid>"
Provides some statistics

.IP "kill -31 <pid>"
provides some informations

.SH BUGS
There can be some bugs - why not?
When you find some, write an email to c00clupea@gmail.com

.SH OTHER INCONVENIENCE
You find somethin not very convenient, you want to have some special honeypot adapter or plugin...?
Solve it and share it...c00clupea is open source

.SH SEE ALSO
you will already know them..
