/**
 *
 * cooclupea Honeypot
 * <*))><
 *
 * (C) 2014 by Christoph Pohl (c00clupea@googlemail.com)
 * released under the GPLv.2
 *
 * File:	c00s_NUM_APPLETS.h
 * created: 	Tue Feb  3 06:38:49 2015
 * author:  	Christoph Pohl <c00clupea@gmail.com>
 */
/**In busybox this file is autogenerated see /applets/applet_tables.c
However we override all those settings, but it is deeply inside the original ash code
To avoid complications, we use this creepy stuff...
**/

#ifndef C00S_NUM_APPLETS_H
#define C00S_NUM_APPLETS_H

#define NUM_APPLETS 42 //Just a number greater than 0

#endif /* C00S_NUM_APPLETS_H */
